version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - 'anexia/system-engineering'

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
    reviewers:
      - 'anexia/system-engineering'

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - 'anexia/system-engineering'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - 'anexia/system-engineering'
