// Package anxcloud provides Terraform resources for Anexia Cloud services.
// This file contains helper functions for DNS record operations.
package anxcloud

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	clouddnsv1 "go.anx.io/go-anxcloud/pkg/apis/clouddns/v1"
)

// generateContentHash creates a stable hash-based identifier for Terraform resource IDs
// based on the record's unique properties (zone, name, type, rdata, ttl)
// This replaces the fake UUID system with content-based identification
func generateContentHash(zoneName, recordName, recordType, rdata string, ttl int) string {
	// Create a deterministic string based on the record's unique properties
	// Include TTL in the hash since it's a mutable field that affects record identity
	key := fmt.Sprintf("%s|%s|%s|%s|%d", zoneName, recordName, recordType, rdata, ttl)

	// Generate SHA256 hash of the key for stable identification
	hash := sha256.Sum256([]byte(key))
	hashStr := hex.EncodeToString(hash[:])

	// Use first 32 characters of hash as resource ID
	// This provides sufficient uniqueness while being deterministic
	return hashStr[:32]
}

// isFakeUUID checks if an ID looks like a fake UUID generated by the old system
func isFakeUUID(id string) bool {
	// Fake UUIDs are in format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	uuidRegex := regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)
	return uuidRegex.MatchString(id)
}

// isContentHash checks if an ID looks like a content hash generated by the new system
func isContentHash(id string) bool {
	// Content hashes are 32-character hex strings
	hashRegex := regexp.MustCompile(`^[0-9a-f]{32}$`)
	return hashRegex.MatchString(id)
}

func dnsRecordFromResourceData(d *schema.ResourceData) clouddnsv1.Record {
	return clouddnsv1.Record{
		Type:      d.Get("type").(string),
		Name:      d.Get("name").(string),
		ZoneName:  d.Get("zone_name").(string),
		Region:    d.Get("region").(string),
		RData:     d.Get("rdata").(string),
		TTL:       d.Get("ttl").(int),
		Immutable: d.Get("immutable").(bool),
	}
}

// DNSRecordData handles conversion between Terraform and API formats for DNS record data.
// TXT records require special handling: API expects quoted values, Terraform uses unquoted.
type DNSRecordData struct {
	Type  string
	RData string
}

// ToAPIFormat converts record data to API format.
// For TXT records, adds outer quotes if not already quoted.
// For other record types, returns data unchanged.
func (d *DNSRecordData) ToAPIFormat() string {
	if d.Type == "TXT" && !isQuotedString(d.RData) {
		return `"` + d.RData + `"`
	}
	return d.RData
}

// FromAPIFormat converts record data from API format to Terraform format.
// For TXT records, strips outer quotes.
// For other record types, returns data unchanged.
func (d *DNSRecordData) FromAPIFormat() string {
	if d.Type == "TXT" {
		return stripOuterQuotes(d.RData)
	}
	return d.RData
}
