name: Documentation

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  GO111MODULE: on

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: avto-dev/markdown-lint@v1
      with:
        config: '.markdownlint.yml'
        args: 'docs'
  terraform-fmt:
    runs-on: ubuntu-latest
    container: golang:1.16-stretch
    steps:
    - uses: actions/checkout@v2
    - run: |
        go get github.com/katbyte/terrafmt
        terrafmt diff docs/ --check --pattern '*.md'
  misspell:
    runs-on: ubuntu-latest
    container: golang:1.16-stretch
    steps:
    - uses: actions/checkout@v2
    - run: |
        go get github.com/client9/misspell/cmd/misspell
        misspell -error -source text docs/
