name: Code quality

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    types: 
    - opened
    - synchronize
    - reopened
    - ready_for_review
  workflow_dispatch: {}

jobs:
  docs-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Check for spelling errors
      run: make misspell

    - name: Check HCL format
      run: make terrafmt

  code-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Check code format
      run: make fmtcheck

    - name: Lint code
      run: make go-lint

  dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: run depscheck
      run: make depscheck

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: run unit tests
      run: make test

  integration-tests:
    if: ${{ ! github.event.pull_request.draft && github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Run acceptance tests
      run: make testacc
      env:
        ANEXIA_TOKEN: ${{ secrets.ANEXIA_TOKEN }}
        ANEXIA_LOCATION_ID: 52b5f6b2fd3a4a7eaaedf1a7c019e9ea
        ANEXIA_VLAN_ID: 00a239d617504e4ab49122efe0d27657
